AWSTemplateFormatVersion: 2010-09-09
Description: >-
  instructor-portal-backend
Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowMethods: "'GET,PUT,POST,DELETE,OPTIONS'"
      # AllowCredentials: true
  Function:
    Layers:
      - !Ref RuntimeDependenciesLayer
    Runtime: nodejs18.x
    MemorySize: 128
    Timeout: 100
    Environment:
      Variables:
        SHARED_SECRETS_ID: 'test'

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  ExampleProject:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: "'*'"
        # AllowOrigin: "'localhost:3000'"
        AllowHeaders: "'Content-Type,Referer,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Referer-Override'"
        AllowMethods: "'GET,PUT,POST,DELETE,OPTIONS'"
        # AllowCredentials: true
      Description: Example structure for serverless with AWS SAM
      EndpointConfiguration:
        Type: REGIONAL
      Auth:
        DefaultAuthorizer: CustomAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CustomAuthorizer:
            FunctionPayloadType: REQUEST
            Identity:
              ReauthorizeEvery: 1800 # Cache for 30 minutes
              Headers:
                - Authorization
            FunctionArn: !GetAtt authenticatorFunction.Arn

  authenticatorFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: handlers/authenticator.handler
      Runtime: nodejs18.x
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:instructor_portal_okta_credentials-*'
  helloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: handlers/helloworld.handler
      Runtime: nodejs18.x
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref InstructorPortal
            Path: /hello
            Method: get
  RuntimeDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      LayerName: RuntimeDependencies
      Description: Runtime dependencies for Lambdas
      ContentUri: ./
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Retain
# Outputs:
#   WebEndpoint:
#     Description: "API Gateway endpoint URL for Prod stage"
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

